# Some constants used by the Session class

DEFAULT_HOST = 'localhost'
DEFAULT_PORT = 3333
DEFAULT_USER = None
DEFAULT_PASSWORD = None
DEFAULT_CHARSET = 'utf-8'
DEFAULT_TIMEOUT_CONNECT = 3.25
DEFAULT_TIMEOUT_RESPONSE = 27
DEFAULT_RETRIES = 3
